### PR TITLE
fix line wrapping

### LINKED ISSUE #25: Edit .gitreview description not wrapped
The description is not wrapped in multiple lines

image

### PR DESCRIPTION
**Pull request by thimmy687**
This commit change a textbox into a label

before:
image

after:

image

fix #25

### CODE REVIEW

File: src/GitExtensions.GerritPlugin/FormGitReview.cs [hunk 1]
```diff
@@ -26,6 +26,17 @@ public sealed partial class FormGitReview : GitExtensionsForm, IGitUICommandsSou
...
+            $"gitreview to setup Gerrit.{Environment.NewLine + Environment.NewLine}" +
+            $"Example configuration{Environment.NewLine + Environment.NewLine}" +
+            $"[gerrit]{Environment.NewLine}" +
+            $"host = review.example.com{Environment.NewLine}" +
+            $"port = 29418{Environment.NewLine}" +
+            $"project = department / project.git{Environment.NewLine}" +
+            $"defaultbranch = master{Environment.NewLine}" +
+            $"defaultremote = review{Environment.NewLine}" +
+            $"defaultrebase = 0");
+
```
Comment (RussKie) [inline src/GitExtensions.GerritPlugin/FormGitReview.cs:39]: Please use verbatim string `@$"..."` instead of multiple concatenations.

File: src/GitExtensions.GerritPlugin/FormGitReview.cs [hunk 2]
```diff
@@ -47,6 +58,7 @@ public FormGitReview(IGitUICommands uiCommands)
             : base(true)
         {
             InitializeComponent();
+            this.label1.Text = _description.ToString();
```
Comment (RussKie) [inline src/GitExtensions.GerritPlugin/FormGitReview.cs:61]:
```suggestion
            this.label1.Text = _description.Text;
```

**Review by RussKie — CHANGES_REQUESTED** [review]

File: src/GitExtensions.GerritPlugin/FormGitReview.cs (hunk 1 above)
Comment (thimmy687) [reply src/GitExtensions.GerritPlugin/FormGitReview.cs:39]: done

Comment (RussKie) [reply src/GitExtensions.GerritPlugin/FormGitReview.cs:39]: Are you sure this is correct? Verbatim string preserves newline chars, so `{Environment.NewLine}` shouldn't be required.

File: src/GitExtensions.GerritPlugin/FormGitReview.cs [hunk 3]
```diff
@@ -26,6 +26,17 @@ public sealed partial class FormGitReview : GitExtensionsForm, IGitUICommandsSou
...
+        private readonly TranslationString _description = new TranslationString(@$"Provide the configuration for{Environment.NewLine}
+            gitreview to setup Gerrit.{Environment.NewLine + Environment.NewLine}
+            Example configuration{Environment.NewLine + Environment.NewLine}
+            [gerrit]{Environment.NewLine}
+            host = review.example.com{Environment.NewLine}
+            port = 29418{Environment.NewLine}
+            project = department / project.git{Environment.NewLine}
+            defaultbranch = master{Environment.NewLine}
+            defaultremote = review{Environment.NewLine}
+            defaultrebase = 0");
```
Comment (RussKie) [inline src/GitExtensions.GerritPlugin/FormGitReview.cs:38]:
```suggestion
        private readonly TranslationString _description = new TranslationString(@$"Example configuration

[gerrit]
host = review.example.com
port = 29418
project = department/project.git
defaultbranch = master
defaultremote = review
defaultrebase = 0");
```

**Review by RussKie — APPROVED** [review]

**Comment by RussKie** [comment]
The build is failing, which isn't caused by this PR, but it's broken none the less.

**Comment by thimmy687** [comment]
Hi @RussKie,

what is about this PR #23 ?

If this is merged, we can rebase on it and it will work, but than we can't release anymore for GE version 3.4 :/

So, please tell me what can/should I do?

**Comment by mast-eu** [comment]
I suggest to rebase on master (should be working now, am I right?).

> but than we can't release anymore for GE version 3.4 :/

True, but the master branch of each plugin should still always point to the GE master.
If a release for GE 3.4 should be needed, this change would be cherry-picked to the release branch.
But since we have GE 3.5 already around the corner I don't think this would be even necessary right now. This fix will go straight into an updated version of GerritPlugin, which targets GE 3.5.

File: src/GitExtensions.GerritPlugin/FormGitReview.cs [hunk 4]
```diff
@@ -26,6 +26,16 @@ public sealed partial class FormGitReview : GitExtensionsForm, IGitUICommandsSou
...
 
+        private readonly TranslationString _description = new TranslationString(@$"Example configuration
+
+                                                                                   [gerrit]
+                                                                                   host=review.example.com
+                                                                                   port=29418
+                                                                                   project=department/project.git
+                                                                                   defaultbranch=master
+                                                                                   defaultremote=review
+                                                                                   defaultrebase=0");
```
Comment (RussKie) [inline src/GitExtensions.GerritPlugin/FormGitReview.cs:37]: Just make sure these leading spaces won't be a problem
```suggestion
        private readonly TranslationString _description = new TranslationString(@$"Example configuration

[gerrit]
host=review.example.com
port=29418
project=department/project.git
defaultbranch=master
defaultremote=review
defaultrebase=0");
```

**Review by RussKie — APPROVED** [review]

**Review by RussKie — APPROVED** [review]

**Comment by RussKie** [comment]
Thank you. Merge at will

**Comment by mast-eu** [comment]
Thank you.
